var ganzzahl = 4;
var fließkommazahl = 4.4;
var string = 'Hallo';
var boolean = true;
var ganzzahlObjekt = Number(4);
var fließkommazahlObjekt = Number(4.4);
var stringObjekt = String('Hallo');
var booleanObjekt = Boolean(true);
console.log(typeof ganzzahl); // number
console.log(typeof ganzzahlObjekt); // object
console.log(typeof fließkommazahl); // number
console.log(typeof fließkommazahlObjekt); // object
console.log(typeof string); // string
console.log(typeof stringObjekt); // object
console.log(typeof boolean); // boolean
console.log(typeof booleanObjekt); // object